theme: jekyll-theme-cayman
title: French Language Learning 
description: Sutharsan Indrachith - 180347324
description: This website is designed to provide an introduction to France and the French language. The site includes range of activites and multimedia presentation to provide effective language learning.
github:
  aboutfrench: aboutfrench.html
  frenchvocab: frenchvocab.html
  frenchphrases: frenchphrases.html
  francelocation: francelocation.html
  furtherstudy: furtherstudy.html
